### ISSUE TITLE
RabbitMQ support

### ISSUE THREAD

**Issue by Rades98** [Rades98/FluentTesting#36]
Add support for RabbitMQ using predefined API, add support to create queues and exchanges with routing keys without dependency on rabbit mq library.. use docker commands (ExecAsync on container) to achieve this..

**Comment by gmottajr** [comment]
Hi @Rades98,

I'd be happy to help with adding RabbitMQ support to **FluentTesting**. Before diving in, I have a few questions to ensure I understand the requirements and your vision for this feature:

### 1. Predefined API for RabbitMQ:
Could you clarify what you mean by "predefined API"? Are you referring to a specific set of methods or interfaces that should be provided for interacting with RabbitMQ, or are you looking for more flexibility in how users can interact with RabbitMQ?

### 2. Queue and Exchange Management:
The task involves supporting the creation of queues and exchanges with routing keys. Do you have a preference for how this should be defined in the API? Should users specify these parameters declaratively, or do you envision a more programmatic approach?

### 3. No Dependency on RabbitMQ Library:
The goal is to avoid a direct dependency on the RabbitMQ library. Would you like to use Docker commands (via `ExecAsync` on the container) to interact with RabbitMQ, as mentioned? How should the API abstract this to make it easy for users to configure RabbitMQ without having to deal with the underlying Docker commands themselves?

### 4. Docker Integration:
Are there any existing utilities or patterns within **FluentTesting** that we should align with for managing RabbitMQ containers via Docker? For instance, how do you envision handling container lifecycles (starting, stopping, cleanup)?

### 5. Unit Tests and Integration Tests:
Are there existing tests related to container management and other services (like Kafka, Redis)? Would you like me to add specific tests for RabbitMQ support, such as validating queue creation, exchange bindings, or message routing?

### 6. Acceptance Criteria:
Can you provide more details on the acceptance criteria for this feature? Some possible criteria could be:
- The ability to spin up a RabbitMQ container via Docker.
- Users can configure RabbitMQ with specific queues, exchanges, and routing keys.
- The API should not directly depend on the RabbitMQ library but should offer necessary functionality via Docker commands.
- Tests validate that the queues and exchanges are created correctly and can handle routing as expected.

Once I have more details, I’ll be able to start implementing this feature and ensure it integrates well with the existing system.

Looking forward to working on this!

Best,  
Gerson Jr.

**Comment by Rades98** [comment]
Hi Gerson,

Thank you so much for your initiative to help with adding RabbitMQ support to FluentTesting! However, I’ve already started working on the solution. You’re welcome to take a look at the PR and let me know if you think anything is missing or if you have any suggestions.

If you still want to contribute, feel free to add any additional technologies in the same style as those already in the repo. Just please avoid adding any dependencies other than Testcontainers to prevent integration issues that might arise from older library versions for potential users.

Thanks again for reaching out!

Best,

Radek

**Comment by Rades98** [comment]
# Support for RabbitMQ Has Been Added  

- **Dockerized RabbitMQ Management Studio:** Introduced integration with a Dockerized RabbitMQ Management Studio in the FluentTesting library code, ensuring there is no dependency on the RabbitMQ Client library.  
- **Publish/Consumption Testing:** Added support for testing message publishing and consumption workflows.  
- **Queue and Exchange Management:** Added functionality for creating queues, exchanges, routing keys, and bindings.  
- **Documentation and Examples:** Included new documentation, a sample application, and its corresponding tests.  

I’m open to discussions about these changes or suggestions for additional features—feel free to share your thoughts in the comments or create a new issue if something relevant is missing!

**Comment by gmottajr** [comment]
I'm sorry @Rades98, 
Ended up getting busy in other projects this weekend and missed you message. Please apologize.
Let try again in other issue, how about that?
Please let me know if you have something that can be assigned to me.
Thank you very much!

**Comment by Rades98** [comment]
Hey @gmottajr,
No worries at all, I completely understand how things can get busy! I’ve sent you an invite to collaborate, so you should now have access to the repository.

Feel free to assign yourself any open issue that interests you. If you’re looking for something to get started, adding support for PostgreSQL could be a good lighter task to begin with.

If you find something missing, you’re welcome to create your own issue and work on it. Also, if you’ve noticed a bug, have suggestions for improvements, or can help with documentation, I’d be grateful for any contributions!

Let me know if you need anything or have questions. Thanks again for your willingness to help!
